---
# ---------------- Install Helm ----------------
- name: Install Helm
  become: yes
  shell: |
    curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  args:
    creates: /usr/local/bin/helm

# ---------------- Add Prometheus Helm Repo ----------------
- name: Add Prometheus Helm repository
  become: yes
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config
  command: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
  failed_when: false

- name: Update Helm repositories
  become: yes
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config
  command: helm repo update

# ---------------- Create Namespace ----------------
- name: Create monitoring namespace
  become: yes
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config
  command: kubectl create namespace monitoring
  failed_when: false

# ---------------- Install Prometheus Stack ----------------
- name: Install kube-prometheus-stack
  become: yes
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config
  command: >
    helm install monitoring prometheus-community/kube-prometheus-stack
    --namespace monitoring
  failed_when: false

# ---------------- Patch Grafana Service ----------------
- name: Patch Grafana service to NodePort
  become: yes
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config
  command: >
    kubectl patch svc monitoring-grafana -n monitoring
    -p '{"spec":{"type":"NodePort"}}'

# ---------------- Get Grafana Port ----------------
- name: Get Grafana NodePort
  become: yes
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config
  shell: >
    kubectl get svc monitoring-grafana -n monitoring
    -o jsonpath='{.spec.ports[0].nodePort}'
  register: grafana_port

- name: Show Grafana URL
  debug:
    msg: "Grafana URL: http://<EC2_PUBLIC_IP>:{{ grafana_port.stdout }}"
