---
- name: Install conntrack (required for Minikube)
  apt:
    name: conntrack
    state: present

- name: Download Minikube
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /usr/local/bin/minikube
    mode: '0755'
