---
- name: Install conntrack
  apt:
    name: conntrack
    state: present

- name: Download Minikube
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /usr/local/bin/minikube
    mode: '0755'

- name: Start Minikube using Docker driver
  become_user: ubuntu
  command: minikube start --driver=docker
  args:
    creates: /home/ubuntu/.kube/config
