---
- name: Download kubectl
  become: yes
  get_url:
    url: https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: '0755'

# ---------------- Jenkins Kubernetes Access ----------------

- name: Ensure Jenkins .kube directory exists
  become: yes
  file:
    path: /var/lib/jenkins/.kube
    state: directory
    owner: jenkins
    group: jenkins
    mode: '0755'

- name: Ensure Jenkins .minikube directory exists
  become: yes
  file:
    path: /var/lib/jenkins/.minikube
    state: directory
    owner: jenkins
    group: jenkins
    mode: '0755'

- name: Copy kubeconfig to Jenkins
  become: yes
  copy:
    src: /home/ubuntu/.kube/config
    dest: /var/lib/jenkins/.kube/config
    owner: jenkins
    group: jenkins
    mode: '0644'
    remote_src: yes

- name: Copy Minikube certificates to Jenkins
  become: yes
  copy:
    src: /home/ubuntu/.minikube/
    dest: /var/lib/jenkins/.minikube/
    owner: jenkins
    group: jenkins
    mode: '0755'
    remote_src: yes

- name: Update kubeconfig certificate paths for Jenkins
  become: yes
  replace:
    path: /var/lib/jenkins/.kube/config
    regexp: '/home/ubuntu/.minikube'
    replace: '/var/lib/jenkins/.minikube'
