pipeline {
    agent any

    environment {
        DOCKERHUB_USER = "sadishdocker"
        BACKEND_IMAGE  = "${DOCKERHUB_USER}/three-tier-backend"
        FRONTEND_IMAGE = "${DOCKERHUB_USER}/three-tier-frontend"
        IMAGE_TAG      = "${BUILD_NUMBER}"
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/sadish2006/Three-tier-application-Resume.git'
            }
        }

        stage('Backend Unit Tests') {
            steps {
                dir('app/backend') {
                    sh '''
                      set -e
                      npm ci
                      npm test || echo "No tests found, skipping"
                    '''
                }
            }
        }

        stage('Frontend Unit Tests') {
            steps {
                dir('app/frontend') {
                    sh '''
                      set -e
                      npm ci
                      npm test || echo "No tests found, skipping"
                    '''
                }
            }
        }

        stage('Build Docker Images') {
            steps {
                sh """
                  docker build -t ${BACKEND_IMAGE}:${IMAGE_TAG} app/backend
                  docker build -t ${FRONTEND_IMAGE}:${IMAGE_TAG} app/frontend
                """
            }
        }

        stage('Tag & Push Images to Docker Hub') {
            steps {
                withDockerRegistry(
                    credentialsId: 'docker-creds',
                    url: 'https://index.docker.io/v1/'
                )  {
                    sh """
                      set -e

                      docker tag ${BACKEND_IMAGE}:${IMAGE_TAG} ${BACKEND_IMAGE}:latest
                      docker tag ${FRONTEND_IMAGE}:${IMAGE_TAG} ${FRONTEND_IMAGE}:latest

                      docker push ${BACKEND_IMAGE}:${IMAGE_TAG}
                      docker push ${BACKEND_IMAGE}:latest

                      docker push ${FRONTEND_IMAGE}:${IMAGE_TAG}
                      docker push ${FRONTEND_IMAGE}:latest
                    """
                    }
               }
            }
    
        stage('Update K8s Manifests') {
            steps {
                sh """
                   sed -i 's|${BACKEND_IMAGE}:latest|${BACKEND_IMAGE}:${IMAGE_TAG}|g' k8s/backend-deployment.yaml
                   sed -i 's|${FRONTEND_IMAGE}:latest|${FRONTEND_IMAGE}:${IMAGE_TAG}|g' k8s/frontend-deployment.yaml
                """
            }
        }

        stage('Deploy to Kubernetes (Minikube)') {
            steps {
                sh """
                   kubectl apply -f k8s/backend-deployment.yaml
                   kubectl apply -f k8s/backend-service.yaml
                   kubectl apply -f k8s/frontend-deployment.yaml
                   kubectl apply -f k8s/frontend-service.yaml
                """
            }
        }

        stage('Verify Deployment') {
            steps {
                sh """
                   kubectl rollout status deployment/backend
                   kubectl rollout status deployment/frontend
                   kubectl get pods
                   kubectl get svc
                """
            }
        }
    }
    post {
        success {
            echo "✅ CI pipeline completed successfully"
        }
        failure {
            echo "❌ CI pipeline failed"
        }
    }
}

 


