pipeline {
    agent any

    options {
        timestamps()
        disableConcurrentBuilds()
    }

    environment {
        DOCKERHUB_USER = "sadishaws"
        BACKEND_IMAGE  = "${DOCKERHUB_USER}/ticket-booking-app-frontend"
        FRONTEND_IMAGE = "${DOCKERHUB_USER}/ticket-booking-app-backend"
        IMAGE_TAG      = "${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/awssadish/Ticket-Booking-App.git'
            }
        }

        stage('Frontend Unit Tests') {
            steps {
                dir('app/frontend') {
                    sh '''
                      set -e
                      npm ci
                      npm test || echo "No tests found, skipping"
                    '''
                }
            }
        }

        stage('Build Docker Images') {
            steps {
                sh """
                  docker build -t ${BACKEND_IMAGE}:${IMAGE_TAG} app/backend
                  docker build -t ${FRONTEND_IMAGE}:${IMAGE_TAG} app/frontend
                """
            }
        }

        stage('Tag & Push Images to Docker Hub') {
            steps {
                withDockerRegistry(
                    credentialsId: 'docker-creds',
                    url: 'https://index.docker.io/v1/'
                ) {
                    sh """
                      set -e

                      docker tag ${BACKEND_IMAGE}:${IMAGE_TAG} ${BACKEND_IMAGE}:latest
                      docker tag ${FRONTEND_IMAGE}:${IMAGE_TAG} ${FRONTEND_IMAGE}:latest

                      docker push ${BACKEND_IMAGE}:${IMAGE_TAG}
                      docker push ${BACKEND_IMAGE}:latest

                      docker push ${FRONTEND_IMAGE}:${IMAGE_TAG}
                      docker push ${FRONTEND_IMAGE}:latest
                    """
                }
            }
        }

        stage('Deploy to Kubernetes (Minikube)') {
            steps {
                sh """
                  kubectl set image deployment/backend backend=${BACKEND_IMAGE}:${IMAGE_TAG} --record
                  kubectl set image deployment/frontend frontend=${FRONTEND_IMAGE}:${IMAGE_TAG} --record
                """
            }
        }

        stage('Verify Deployment') {
            steps {
                sh """
                   kubectl rollout status deployment/backend
                   kubectl rollout status deployment/frontend
                   kubectl get pods
                   kubectl get svc
                """
            }
        }
    }

    post {
        success {
            echo "✅ CI/CD pipeline completed successfully"
        }
        failure {
            echo "❌ CI/CD pipeline failed"
        }
    }
}
